# Docker Compose config for eit

version: '3.7'
services:
  backend:
    container_name: eit-backend
    image: ntnutio48522020gr2/backend:bleeding
    environment:
    - TZ=Europe/Oslo
    - APP_UID=900
    - APP_GID=900
    # TODO add superuser info on first run
    - SUPERUSER_USERNAME=hon
    - SUPERUSER_EMAIL=haavard.nordstrand@gmail.com
    - SUPERUSER_PASSWORD=password
    - SUPERUSER_INACTIVE=false
    - NO_START=false
    volumes:
    - ./backend/settings.py:/app/src/settings/local.py:ro
    - ./backend/db.sqlite3:/app/db.sqlite3:rw
    - ./log/backend/:/app/log:rw
    - ./www/backend/static:/app/static:rw
    #- ./backend/uwsgi.dev.ini:/app/uwsgi.ini:rw
    restart: "always"
#    depends_on:
#    - db

  frontend:
    container_name: eit-frontend
    image: ntnutio48522020gr2/frontend:bleeding
    environment:
    - TZ=Europe/Oslo
    volumes:
    - ./frontend/config.js:/www/config.js:ro
    restart: "always"

#  db:
#    container_name: eit-backend-db
#    image: postgres
#    # postgres doesn't like being run as a specified user, so databse files have a weird owner
#    # postgres doesn't write log files by default, so no log dir is bound
#    environment:
#    - POSTGRES_USER=postgres
#    - POSTGRES_PASSWORD=HIDDEN
#    volumes:
#    - ./db/data:/var/lib/postgresql/data:rw
#    restart: "always"

  nginx:
    image: nginx:1.17-alpine
    container_name: eit-nginx
    environment:
    - TZ=Europe/Oslo
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/sites/:/etc/nginx/sites/:ro
    - ./log/nginx/:/var/log/nginx/:rw
    - ./certs/eit.haavard.cloud.cert:/config/certs/eit.haavard.cloud.cert:ro
    - ./certs/eit.haavard.cloud.key:/config/certs/eit.haavard.cloud.key:ro
    - ./certs/api.eit.haavard.cloud.cert:/config/certs/api.eit.haavard.cloud.cert:ro
    - ./certs/api.eit.haavard.cloud.key:/config/certs/api.eit.haavard.cloud.key:ro
    - ./www:/config/www/:ro
    ports:
    - 80:80
    - 443:443
    restart: "always"
