# Docker Compose config for eit-backend

version: '3.7'
services:
  app:
    container_name: eit-backend-app
    image: ntnutio48522020gr2/backend:bleeding
    environment:
    - APP_UID=999
    - APP_GID=998
    # TODO add superuser info on first run
    #- SUPERUSER_USERNAME=hon
    #- SUPERUSER_EMAIL=haavard.nordstrand@gmail.com
    #- SUPERUSER_PASSWORD=monstermonster
    #- SUPERUSER_INACTIVE=true
    - NO_START=false
    volumes:
    - ./settings.py:/app/src/settings/local.py:ro
    - ./db.sqlite3:/app/db.sqlite3:rw
    - ./log/app/:/app/log:rw
    - ./www/static:/app/static:rw
    restart: "always"
#    depends_on:
#    - db

#  db:
#    container_name: eit-backend-db
#    image: postgres
#    # postgres doesn't like being run as a specified user, so databse files have a weird owner
#    # postgres doesn't write log files by default, so no log dir is bound
#    environment:
#    - POSTGRES_USER=postgres
#    - POSTGRES_PASSWORD=HIDDEN
#    volumes:
#    - ./db/data:/var/lib/postgresql/data:rw
#    restart: "always"

  nginx:
    image: nginx:1.17-alpine
    container_name: eit-backend-nginx
    environment:
    - TZ=Europe/Oslo
    volumes:
    - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx-config/sites/:/etc/nginx/sites/:ro
    - ./log/nginx/:/var/log/nginx/:rw
    - ./certs/eit.haavard.cloud.cert:/config/certs/eit.haavard.cloud.cert:ro
    - ./certs/eit.haavard.cloud.key:/config/certs/eit.haavard.cloud.key:ro
    - ./www:/config/www/:ro
    ports:
    - 80:80
    - 443:443
    restart: "always"
